export const actions = {
  CHECK_UPDATES: "CHECK_UPDATES",
  CHECK_UPDATES_SUCCESS: "CHECK_UPDATES_SUCCESS",
  CHECK_UPDATES_FAILURE: "CHECK_UPDATES_FAILURE",

  ADD_DIAGNOSTIC: "ADD_DIAGNOSTIC",
  ADD_DIAGNOSTIC_SUCCESS: "ADD_DIAGNOSTIC_SUCCESS",
  ADD_DIAGNOSTIC_FAILURE: "ADD_DIAGNOSTIC_FAILURE",
};

export default actions;
